insert into BooksAuthors (BookID, AuthorID, AuthorType) values (1, 39, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (2, 51, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (3, 64, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (4, 184, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (5, 210, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (6, 138, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (7, 245, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (8, 9, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (9, 144, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (10, 236, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (11, 131, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (12, 232, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (13, 149, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (14, 183, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (15, 91, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (16, 102, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (17, 51, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (18, 208, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (19, 170, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (20, 102, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (21, 76, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (22, 74, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (23, 165, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (24, 5, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (25, 93, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (26, 183, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (27, 137, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (28, 218, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (29, 169, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (30, 5, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (31, 130, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (32, 226, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (33, 3, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (34, 26, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (35, 53, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (36, 4, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (37, 209, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (38, 196, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (39, 103, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (40, 248, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (41, 132, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (42, 223, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (43, 169, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (44, 108, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (45, 65, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (46, 219, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (47, 171, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (48, 214, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (49, 3, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (50, 7, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (51, 14, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (52, 62, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (53, 12, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (54, 98, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (55, 212, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (56, 124, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (57, 2, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (58, 136, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (59, 156, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (60, 33, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (61, 8, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (62, 188, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (63, 192, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (64, 138, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (65, 69, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (66, 7, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (67, 169, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (68, 152, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (69, 108, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (70, 122, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (71, 159, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (72, 105, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (73, 13, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (74, 59, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (75, 170, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (76, 231, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (77, 3, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (78, 108, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (79, 233, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (80, 152, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (81, 247, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (82, 107, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (83, 189, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (84, 183, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (85, 100, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (86, 244, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (87, 145, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (88, 212, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (89, 162, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (90, 231, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (91, 171, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (92, 62, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (93, 37, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (94, 14, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (95, 88, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (96, 183, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (97, 5, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (98, 124, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (99, 68, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (100, 160, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (101, 188, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (102, 154, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (103, 231, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (104, 85, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (105, 199, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (106, 119, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (107, 107, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (108, 9, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (109, 126, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (110, 238, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (111, 170, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (112, 138, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (113, 156, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (114, 191, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (115, 238, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (116, 68, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (117, 176, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (118, 56, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (119, 249, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (120, 58, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (121, 6, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (122, 224, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (123, 180, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (124, 37, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (125, 10, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (126, 117, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (127, 126, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (128, 119, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (129, 11, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (130, 51, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (131, 13, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (132, 40, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (133, 194, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (134, 136, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (135, 124, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (136, 158, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (137, 202, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (138, 116, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (139, 102, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (140, 165, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (141, 82, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (142, 68, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (143, 128, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (144, 239, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (145, 138, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (146, 137, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (147, 35, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (148, 150, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (149, 160, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (150, 21, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (151, 30, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (152, 90, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (153, 225, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (154, 245, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (155, 98, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (156, 221, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (157, 122, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (158, 164, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (159, 23, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (160, 86, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (161, 24, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (162, 145, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (163, 25, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (164, 95, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (165, 107, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (166, 214, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (167, 58, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (168, 32, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (169, 104, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (170, 10, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (171, 247, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (172, 120, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (173, 194, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (174, 206, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (175, 64, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (176, 159, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (177, 207, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (178, 237, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (179, 142, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (180, 151, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (181, 49, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (182, 103, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (183, 234, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (184, 52, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (185, 12, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (186, 52, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (187, 200, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (188, 92, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (189, 106, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (190, 80, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (191, 174, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (192, 102, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (193, 185, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (194, 119, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (195, 157, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (196, 172, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (197, 35, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (198, 124, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (199, 49, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (200, 190, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (201, 154, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (202, 76, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (203, 79, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (204, 159, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (205, 119, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (206, 64, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (207, 191, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (208, 47, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (209, 94, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (210, 79, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (211, 34, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (212, 209, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (213, 158, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (214, 1, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (215, 224, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (216, 221, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (217, 205, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (218, 246, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (219, 70, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (220, 112, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (221, 122, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (222, 121, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (223, 211, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (224, 12, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (225, 249, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (226, 149, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (227, 77, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (228, 88, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (229, 113, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (230, 70, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (231, 21, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (232, 193, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (233, 208, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (234, 151, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (235, 234, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (236, 210, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (237, 87, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (238, 207, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (239, 209, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (240, 75, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (241, 25, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (242, 141, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (243, 244, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (244, 75, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (245, 211, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (246, 179, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (247, 94, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (248, 130, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (249, 108, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (250, 87, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (251, 14, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (252, 165, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (253, 209, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (254, 31, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (255, 90, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (256, 43, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (257, 22, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (258, 178, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (259, 179, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (260, 78, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (261, 166, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (262, 36, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (263, 126, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (264, 21, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (265, 93, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (266, 46, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (267, 21, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (268, 206, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (269, 59, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (270, 58, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (271, 42, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (272, 39, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (273, 183, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (274, 239, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (275, 106, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (276, 173, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (277, 100, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (278, 66, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (279, 107, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (280, 90, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (281, 220, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (282, 2, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (283, 61, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (284, 160, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (285, 79, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (286, 66, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (287, 192, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (288, 181, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (289, 242, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (290, 121, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (291, 91, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (292, 56, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (293, 124, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (294, 50, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (295, 111, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (296, 233, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (297, 140, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (298, 248, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (299, 95, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (300, 30, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (301, 35, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (302, 166, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (303, 65, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (304, 238, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (305, 108, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (306, 203, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (307, 170, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (308, 70, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (309, 142, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (310, 83, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (311, 58, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (312, 169, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (313, 117, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (314, 119, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (315, 154, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (316, 57, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (317, 156, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (318, 107, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (319, 13, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (320, 43, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (321, 210, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (322, 121, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (323, 244, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (324, 187, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (325, 250, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (326, 62, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (327, 25, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (328, 147, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (329, 132, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (330, 197, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (331, 25, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (332, 65, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (333, 133, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (334, 131, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (335, 126, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (336, 59, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (337, 160, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (338, 228, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (339, 203, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (340, 153, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (341, 233, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (342, 199, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (343, 85, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (344, 219, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (345, 8, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (346, 171, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (347, 122, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (348, 164, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (349, 126, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (350, 86, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (351, 42, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (352, 183, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (353, 195, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (354, 223, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (355, 230, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (356, 141, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (357, 239, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (358, 135, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (359, 243, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (360, 243, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (361, 62, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (362, 136, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (363, 98, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (364, 173, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (365, 32, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (366, 7, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (367, 147, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (368, 5, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (369, 85, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (370, 91, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (371, 206, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (372, 208, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (373, 40, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (374, 156, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (375, 120, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (376, 205, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (377, 6, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (378, 121, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (379, 169, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (380, 30, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (381, 220, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (382, 147, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (383, 202, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (384, 25, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (385, 200, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (386, 34, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (387, 75, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (388, 194, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (389, 122, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (390, 239, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (391, 176, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (392, 227, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (393, 69, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (394, 239, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (395, 142, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (396, 242, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (397, 20, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (398, 162, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (399, 210, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (400, 62, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (401, 174, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (402, 66, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (403, 104, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (404, 219, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (405, 163, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (406, 164, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (407, 200, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (408, 164, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (409, 196, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (410, 105, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (411, 71, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (412, 24, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (413, 181, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (414, 46, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (415, 178, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (416, 5, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (417, 103, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (418, 126, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (419, 76, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (420, 10, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (421, 120, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (422, 216, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (423, 140, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (424, 114, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (425, 123, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (426, 92, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (427, 20, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (428, 227, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (429, 74, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (430, 24, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (431, 220, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (432, 58, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (433, 246, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (434, 103, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (435, 33, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (436, 101, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (437, 69, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (438, 144, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (439, 228, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (440, 3, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (441, 30, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (442, 136, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (443, 229, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (444, 229, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (445, 135, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (446, 68, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (447, 95, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (448, 37, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (449, 146, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (450, 207, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (451, 107, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (452, 58, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (453, 18, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (454, 59, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (455, 20, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (456, 59, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (457, 34, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (458, 83, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (459, 3, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (460, 192, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (461, 213, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (462, 230, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (463, 217, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (464, 124, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (465, 19, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (466, 7, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (467, 126, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (468, 4, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (469, 132, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (470, 165, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (471, 215, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (472, 234, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (473, 157, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (474, 184, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (475, 37, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (476, 39, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (477, 142, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (478, 139, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (479, 130, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (480, 44, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (481, 77, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (482, 8, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (483, 178, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (484, 69, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (485, 184, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (486, 15, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (487, 218, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (488, 26, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (489, 210, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (490, 145, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (491, 28, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (492, 34, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (493, 37, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (494, 190, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (495, 87, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (496, 33, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (497, 94, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (498, 159, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (499, 93, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (500, 65, 'Main Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (8, 93, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (9, 31, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (10, 103, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (11, 82, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (12, 98, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (13, 177, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (14, 198, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (15, 239, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (16, 215, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (29, 11, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (51, 196, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (52, 217, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (53, 196, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (57, 82, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (58, 89, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (59, 64, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (60, 92, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (61, 143, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (62, 218, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (73, 23, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (74, 211, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (75, 135, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (82, 116, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (83, 244, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (91, 172, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (92, 158, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (97, 210, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (98, 118, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (99, 21, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (101, 20, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (112, 60, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (113, 129, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (114, 176, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (116, 126, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (117, 107, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (118, 14, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (119, 93, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (120, 60, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (121, 227, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (122, 143, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (123, 119, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (124, 186, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (131, 153, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (132, 2, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (146, 81, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (158, 62, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (159, 134, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (160, 149, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (161, 22, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (162, 241, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (163, 53, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (168, 189, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (169, 60, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (170, 28, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (171, 65, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (172, 26, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (173, 43, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (174, 50, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (175, 197, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (178, 96, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (179, 160, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (180, 145, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (181, 226, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (182, 175, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (183, 66, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (184, 104, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (197, 128, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (198, 66, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (199, 150, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (200, 236, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (206, 91, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (207, 192, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (208, 30, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (209, 81, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (210, 223, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (211, 21, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (213, 178, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (214, 105, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (216, 184, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (217, 247, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (220, 60, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (222, 137, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (223, 146, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (225, 237, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (226, 36, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (227, 180, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (229, 40, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (231, 211, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (232, 248, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (235, 225, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (236, 242, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (238, 40, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (241, 218, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (242, 91, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (244, 56, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (245, 3, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (247, 221, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (248, 246, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (250, 30, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (252, 166, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (254, 245, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (255, 153, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (256, 235, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (257, 139, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (259, 6, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (260, 107, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (261, 1, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (262, 88, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (263, 234, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (264, 204, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (265, 88, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (266, 98, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (267, 106, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (269, 52, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (274, 128, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (275, 64, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (276, 170, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (277, 134, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (278, 4, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (280, 81, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (281, 121, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (282, 47, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (284, 184, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (285, 48, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (286, 208, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (287, 27, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (289, 239, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (296, 146, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (299, 81, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (301, 116, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (304, 35, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (307, 243, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (308, 147, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (310, 176, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (311, 181, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (313, 31, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (315, 80, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (316, 218, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (319, 222, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (320, 230, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (321, 92, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (322, 143, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (326, 187, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (329, 124, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (330, 143, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (332, 177, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (334, 91, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (336, 190, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (339, 46, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (342, 63, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (343, 211, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (345, 66, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (346, 210, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (348, 230, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (349, 200, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (350, 60, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (352, 67, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (353, 96, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (359, 175, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (361, 204, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (362, 194, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (364, 132, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (365, 32, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (367, 42, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (368, 160, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (369, 210, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (370, 115, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (372, 233, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (373, 195, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (375, 22, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (376, 75, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (378, 42, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (379, 174, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (380, 39, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (382, 32, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (383, 114, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (384, 238, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (386, 3, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (389, 93, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (390, 125, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (391, 84, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (392, 228, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (393, 39, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (394, 190, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (397, 64, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (398, 98, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (399, 19, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (402, 109, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (404, 110, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (406, 145, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (407, 129, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (408, 163, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (409, 238, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (411, 1, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (412, 69, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (413, 183, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (414, 221, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (416, 207, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (417, 177, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (418, 61, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (420, 235, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (421, 23, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (424, 219, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (425, 118, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (427, 224, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (428, 163, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (430, 95, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (431, 95, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (432, 152, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (434, 14, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (435, 215, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (437, 57, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (442, 195, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (443, 116, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (444, 145, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (445, 197, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (446, 167, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (449, 206, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (453, 36, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (455, 237, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (457, 75, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (458, 169, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (460, 231, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (462, 105, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (463, 183, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (464, 17, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (467, 117, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (468, 27, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (469, 28, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (470, 52, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (474, 88, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (475, 78, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (476, 121, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (477, 117, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (478, 114, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (481, 31, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (485, 241, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (487, 218, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (488, 195, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (490, 38, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (491, 125, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (492, 99, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (493, 56, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (495, 26, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (496, 81, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (497, 85, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (498, 8, 'Co-Author');
insert into BooksAuthors (BookID, AuthorID, AuthorType) values (499, 235, 'Co-Author');


