insert into Books (BookID, Name, Type, PublicationDate) values (1, 'Whispers of Forgotten Dreams', 'Technical Book', '1954-04-15');
insert into Books (BookID, Name, Type, PublicationDate) values (2, 'The Enigma of Vanishing Echoes', 'Science Book', '1986-06-16');
insert into Books (BookID, Name, Type, PublicationDate) values (3, 'Dance of Celestial Shadows', 'Literary Book', '2015-12-19');
insert into Books (BookID, Name, Type, PublicationDate) values (4, 'Gardens of Temporal Portals', 'Technical Book', '1962-12-15');
insert into Books (BookID, Name, Type, PublicationDate) values (5, 'Fragrance of Wandering Dreams', 'Art Book', '1908-06-03');
insert into Books (BookID, Name, Type, PublicationDate) values (6, 'Return of Lost Thoughts', 'Biography', '1985-04-30');
insert into Books (BookID, Name, Type, PublicationDate) values (7, 'Sunset of the Silver Moon', 'Art Book', '1941-06-08');
insert into Books (BookID, Name, Type, PublicationDate) values (8, 'The Forgotten Dreamweaver', 'Literary Book', '1918-03-04');
insert into Books (BookID, Name, Type, PublicationDate) values (9, 'The Whisper of Forgotten Tales', 'Technical Book', '1986-06-17');
insert into Books (BookID, Name, Type, PublicationDate) values (10, 'Seeker of Lost Emotions', 'Science Book', '1990-07-25');
insert into Books (BookID, Name, Type, PublicationDate) values (11, 'Passage Through the Mirror of Time', 'Technical Book', '1982-12-23');
insert into Books (BookID, Name, Type, PublicationDate) values (12, 'Knights of the Starlight', 'Technical Book', '1969-01-01');
insert into Books (BookID, Name, Type, PublicationDate) values (13, 'Fiery Dance of Magical Lights', 'Art Book', '2009-08-11');
insert into Books (BookID, Name, Type, PublicationDate) values (14, 'Hidden World of Botanical Wonders', 'Art Book', '1985-06-16');
insert into Books (BookID, Name, Type, PublicationDate) values (15, 'The Sound of Silence', 'Science Book', '1908-06-02');
insert into Books (BookID, Name, Type, PublicationDate) values (16, 'Rhythm of Forgotten Streets', 'Technical Book', '1946-08-21');
insert into Books (BookID, Name, Type, PublicationDate) values (17, 'The Island of Lost Memories', 'Technical Book', '1941-11-14');
insert into Books (BookID, Name, Type, PublicationDate) values (18, 'The Light of Forgotten Words', 'Science Book', '1949-06-04');
insert into Books (BookID, Name, Type, PublicationDate) values (19, 'Doors of Timelessness', 'Literary Book', '1952-05-11');
insert into Books (BookID, Name, Type, PublicationDate) values (20, 'Traveler''s Guide to Lost Realms', 'Art Book', '1928-08-26');
insert into Books (BookID, Name, Type, PublicationDate) values (21, 'Chronicles of the Nebula''s Shadow', 'Science Book', '1925-03-27');
insert into Books (BookID, Name, Type, PublicationDate) values (22, 'The Veiled City of Dreams', 'Science Book', '1934-02-15');
insert into Books (BookID, Name, Type, PublicationDate) values (23, 'Symphony of Vanished Hopes', 'Technical Book', '1949-08-31');
insert into Books (BookID, Name, Type, PublicationDate) values (24, 'Echoes from the Misty Vale', 'Technical Book', '2015-10-07');
insert into Books (BookID, Name, Type, PublicationDate) values (25, 'The Forgotten Alchemist''s Journal', 'Literary Book', '1979-06-07');
insert into Books (BookID, Name, Type, PublicationDate) values (26, 'Keys to the Forgotten Kingdom', 'Art Book', '2014-08-31');
insert into Books (BookID, Name, Type, PublicationDate) values (27, 'Whispers in the Eternal Forest', 'Literary Book', '1908-10-11');
insert into Books (BookID, Name, Type, PublicationDate) values (28, 'Beyond the Canvas of Time', 'Literary Book', '1994-02-10');
insert into Books (BookID, Name, Type, PublicationDate) values (29, 'The Silent Echo Chamber', 'Technical Book', '1904-05-12');
insert into Books (BookID, Name, Type, PublicationDate) values (30, 'Secrets of the Enchanted Labyrinth', 'Biography', '1941-07-13');
insert into Books (BookID, Name, Type, PublicationDate) values (31, 'The Lost Symphony of Stars', 'Art Book', '1940-04-10');
insert into Books (BookID, Name, Type, PublicationDate) values (32, 'Footprints in the Sands of Eternity', 'Technical Book', '2000-07-06');
insert into Books (BookID, Name, Type, PublicationDate) values (33, 'The Twilight Reverie', 'Literary Book', '1979-11-10');
insert into Books (BookID, Name, Type, PublicationDate) values (34, 'Arcane Whispers in Forgotten Halls', 'Biography', '1918-04-06');
insert into Books (BookID, Name, Type, PublicationDate) values (35, 'Echoes of a Celestial Siren', 'Technical Book', '1979-12-21');
insert into Books (BookID, Name, Type, PublicationDate) values (36, 'Enchanted Odysseys of Lost Souls', 'Biography', '1918-06-26');
insert into Books (BookID, Name, Type, PublicationDate) values (37, 'The Kaleidoscope of Fading Stars', 'Art Book', '1998-12-08');
insert into Books (BookID, Name, Type, PublicationDate) values (38, 'Scepter of the Astral Nomad', 'Art Book', '1922-05-05');
insert into Books (BookID, Name, Type, PublicationDate) values (39, 'Serenade of the Elusive Cosmos', 'Science Book', '1980-07-20');
insert into Books (BookID, Name, Type, PublicationDate) values (40, 'The Cryptic Oracle''s Riddle', 'Literary Book', '2019-03-02');
insert into Books (BookID, Name, Type, PublicationDate) values (41, 'Dreamscape Chronicles', 'Literary Book', '2011-04-22');
insert into Books (BookID, Name, Type, PublicationDate) values (42, 'The Spectral Waltz', 'Art Book', '1939-11-21');
insert into Books (BookID, Name, Type, PublicationDate) values (43, 'Aetherial Lullaby', 'Biography', '1989-05-24');
insert into Books (BookID, Name, Type, PublicationDate) values (44, 'Shadows in the Crystal Veil', 'Literary Book', '1925-09-24');
insert into Books (BookID, Name, Type, PublicationDate) values (45, 'Whispers of the Ephemeral Muse', 'Literary Book', '1990-11-25');
insert into Books (BookID, Name, Type, PublicationDate) values (46, 'Chronicles of the Celestial Nomad', 'Literary Book', '1903-12-30');
insert into Books (BookID, Name, Type, PublicationDate) values (47, 'Realm of the Vanishing Shadows', 'Art Book', '1976-03-05');
insert into Books (BookID, Name, Type, PublicationDate) values (48, 'Crimson Nebula''s Reflection', 'Technical Book', '1935-02-13');
insert into Books (BookID, Name, Type, PublicationDate) values (49, 'The Forgotten Codex of Dreams', 'Biography', '1942-01-30');
insert into Books (BookID, Name, Type, PublicationDate) values (50, 'Waltz of the Ethereal Veil', 'Art Book', '1958-08-13');
insert into Books (BookID, Name, Type, PublicationDate) values (51, 'Chronicles of the Astral Nomad', 'Science Book', '1971-03-15');
insert into Books (BookID, Name, Type, PublicationDate) values (52, 'Sorcerer''s Lament', 'Science Book', '1976-12-30');
insert into Books (BookID, Name, Type, PublicationDate) values (53, 'Eternal Echoes in Sapphire', 'Art Book', '1922-10-22');
insert into Books (BookID, Name, Type, PublicationDate) values (54, 'The Ethereal Mirage', 'Technical Book', '1939-10-10');
insert into Books (BookID, Name, Type, PublicationDate) values (55, 'Labyrinth of Shifting Realms', 'Literary Book', '1954-05-31');
insert into Books (BookID, Name, Type, PublicationDate) values (56, 'Songs of the Astral Phoenix', 'Biography', '1949-10-27');
insert into Books (BookID, Name, Type, PublicationDate) values (57, 'Harmony in the Forgotten Symphony', 'Biography', '1905-09-07');
insert into Books (BookID, Name, Type, PublicationDate) values (58, 'Waves of the Enchanted Twilight', 'Art Book', '1967-01-26');
insert into Books (BookID, Name, Type, PublicationDate) values (59, 'Pilgrimage Through the Cosmic Tapestry', 'Biography', '1921-09-24');
insert into Books (BookID, Name, Type, PublicationDate) values (60, 'Oracle''s Veil of Whispers', 'Biography', '2008-07-11');
insert into Books (BookID, Name, Type, PublicationDate) values (61, 'The Starlit Compendium', 'Art Book', '2008-06-08');
insert into Books (BookID, Name, Type, PublicationDate) values (62, 'The Ethereal Garden of Lost Melodies', 'Literary Book', '1955-05-01');
insert into Books (BookID, Name, Type, PublicationDate) values (63, 'Beyond the Astral Horizon', 'Art Book', '1937-08-31');
insert into Books (BookID, Name, Type, PublicationDate) values (64, 'The Enchanted Atlas of Shadows', 'Technical Book', '1992-11-26');
insert into Books (BookID, Name, Type, PublicationDate) values (65, 'Crescent Moons of Forgotten Realms', 'Art Book', '1915-01-09');
insert into Books (BookID, Name, Type, PublicationDate) values (66, 'Siren''s Song in the Cosmic Wind', 'Literary Book', '2022-10-04');
insert into Books (BookID, Name, Type, PublicationDate) values (67, 'Labyrinth of the Celestial Wanderer', 'Technical Book', '1911-06-14');
insert into Books (BookID, Name, Type, PublicationDate) values (68, 'Shards of the Ethereal Mirror', 'Biography', '1985-04-01');
insert into Books (BookID, Name, Type, PublicationDate) values (69, 'The Astral Alchemy Codex', 'Science Book', '1954-08-29');
insert into Books (BookID, Name, Type, PublicationDate) values (70, 'Elysian Echoes of the Starborn', 'Technical Book', '1939-08-07');
insert into Books (BookID, Name, Type, PublicationDate) values (71, 'Whispers in the Celestial Embrace', 'Biography', '1979-02-23');
insert into Books (BookID, Name, Type, PublicationDate) values (72, 'The Ephemeral Odyssey', 'Technical Book', '1993-02-27');
insert into Books (BookID, Name, Type, PublicationDate) values (73, 'The Enchanted Glyphs of Time', 'Science Book', '2005-01-08');
insert into Books (BookID, Name, Type, PublicationDate) values (74, 'Shadows in the Whispering Pines', 'Literary Book', '1916-06-11');
insert into Books (BookID, Name, Type, PublicationDate) values (75, 'The Celestial Waltz of Eternity', 'Biography', '2006-11-11');
insert into Books (BookID, Name, Type, PublicationDate) values (76, 'Ephemeral Echoes of the Forgotten', 'Science Book', '1969-12-20');
insert into Books (BookID, Name, Type, PublicationDate) values (77, 'Moonlit Serenade of the Cosmos', 'Art Book', '1993-07-26');
insert into Books (BookID, Name, Type, PublicationDate) values (78, 'The Celestial Odyssey of Dreams', 'Literary Book', '1970-05-09');
insert into Books (BookID, Name, Type, PublicationDate) values (79, 'The Ethereal Echo of Lost Realms', 'Science Book', '1923-07-02');
insert into Books (BookID, Name, Type, PublicationDate) values (80, 'Crimson Veil of Astral Whispers', 'Art Book', '1955-04-15');
insert into Books (BookID, Name, Type, PublicationDate) values (81, 'Lullaby of the Celestial Seraph', 'Art Book', '1979-04-16');
insert into Books (BookID, Name, Type, PublicationDate) values (82, 'Sapphire Labyrinth of Lost Memories', 'Science Book', '1979-04-20');
insert into Books (BookID, Name, Type, PublicationDate) values (83, 'Ethereal Harmony of the Cosmos', 'Technical Book', '1987-07-03');
insert into Books (BookID, Name, Type, PublicationDate) values (84, 'Cascading Stardust Symphony', 'Art Book', '2018-11-13');
insert into Books (BookID, Name, Type, PublicationDate) values (85, 'Chalice of the Celestial Alchemist', 'Science Book', '1911-06-19');
insert into Books (BookID, Name, Type, PublicationDate) values (86, 'Chronicles of the Astral Nomad', 'Biography', '1962-03-17');
insert into Books (BookID, Name, Type, PublicationDate) values (87, 'Ephemeral Enchantments', 'Literary Book', '1945-04-27');
insert into Books (BookID, Name, Type, PublicationDate) values (88, 'The Celestial Ballad of Lost Souls', 'Science Book', '1976-10-23');
insert into Books (BookID, Name, Type, PublicationDate) values (89, 'Specters in the Astral Mist', 'Technical Book', '1955-07-12');
insert into Books (BookID, Name, Type, PublicationDate) values (90, 'Labyrinth of the Whispering Cosmos', 'Literary Book', '1995-07-14');
insert into Books (BookID, Name, Type, PublicationDate) values (91, 'Crimson Dreams of the Celestial Realm', 'Science Book', '1923-04-21');
insert into Books (BookID, Name, Type, PublicationDate) values (92, 'Eternal Echoes of the Forgotten Tome', 'Literary Book', '1979-12-06');
insert into Books (BookID, Name, Type, PublicationDate) values (93, 'Whispers from the Astral Sanctuary', 'Art Book', '2007-11-10');
insert into Books (BookID, Name, Type, PublicationDate) values (94, 'The Ethereal Grimoire of the Stars', 'Art Book', '1936-07-14');
insert into Books (BookID, Name, Type, PublicationDate) values (95, 'Luminous Threads of the Celestial Tapestry', 'Biography', '1964-12-26');
insert into Books (BookID, Name, Type, PublicationDate) values (96, 'Chorus of the Astral Muse', 'Science Book', '1949-05-13');
insert into Books (BookID, Name, Type, PublicationDate) values (97, 'The Ephemeral Whispers of the Starlight', 'Technical Book', '1986-06-28');
insert into Books (BookID, Name, Type, PublicationDate) values (98, 'Harmony of the Celestial Spheres', 'Science Book', '1992-06-06');
insert into Books (BookID, Name, Type, PublicationDate) values (99, 'Labyrinth of the Enchanted Nebula', 'Science Book', '1986-11-15');
insert into Books (BookID, Name, Type, PublicationDate) values (100, 'Crimson Symphony of Forgotten Stars', 'Art Book', '2009-08-02');
insert into Books (BookID, Name, Type, PublicationDate) values (101, 'Chronicles of the Celestial Nomad', 'Technical Book', '2006-03-18');
insert into Books (BookID, Name, Type, PublicationDate) values (102, 'Sorcerer''s Lament', 'Biography', '1945-04-02');
insert into Books (BookID, Name, Type, PublicationDate) values (103, 'Eternal Echoes in Sapphire', 'Biography', '1936-12-26');
insert into Books (BookID, Name, Type, PublicationDate) values (104, 'The Ethereal Mirage', 'Technical Book', '1994-10-03');
insert into Books (BookID, Name, Type, PublicationDate) values (105, 'Songs of the Astral Phoenix', 'Literary Book', '1988-01-25');
insert into Books (BookID, Name, Type, PublicationDate) values (106, 'Harmony in the Forgotten Symphony', 'Biography', '2009-01-16');
insert into Books (BookID, Name, Type, PublicationDate) values (107, 'Waves of the Enchanted Twilight', 'Literary Book', '1982-10-13');
insert into Books (BookID, Name, Type, PublicationDate) values (108, 'Pilgrimage Through the Cosmic Tapestry', 'Art Book', '2011-12-16');
insert into Books (BookID, Name, Type, PublicationDate) values (109, 'Oracle''s Veil of Whispers', 'Science Book', '1929-10-15');
insert into Books (BookID, Name, Type, PublicationDate) values (110, 'The Starlit Compendium', 'Science Book', '1935-01-03');
insert into Books (BookID, Name, Type, PublicationDate) values (111, 'The Ethereal Garden of Lost Melodies', 'Science Book', '1979-04-14');
insert into Books (BookID, Name, Type, PublicationDate) values (112, 'Beyond the Astral Horizon', 'Biography', '1908-10-10');
insert into Books (BookID, Name, Type, PublicationDate) values (113, 'The Enchanted Atlas of Shadows', 'Science Book', '1933-03-24');
insert into Books (BookID, Name, Type, PublicationDate) values (114, 'Crescent Moons of Forgotten Realms', 'Literary Book', '1994-09-27');
insert into Books (BookID, Name, Type, PublicationDate) values (115, 'Siren''s Song in the Cosmic Wind', 'Literary Book', '1986-07-17');
insert into Books (BookID, Name, Type, PublicationDate) values (116, 'Labyrinth of the Celestial Wanderer', 'Biography', '1939-02-17');
insert into Books (BookID, Name, Type, PublicationDate) values (117, 'Shards of the Ethereal Mirror', 'Literary Book', '1968-02-02');
insert into Books (BookID, Name, Type, PublicationDate) values (118, 'The Astral Alchemy Codex', 'Technical Book', '1967-11-11');
insert into Books (BookID, Name, Type, PublicationDate) values (119, 'Elysian Echoes of the Starborn', 'Biography', '1996-07-21');
insert into Books (BookID, Name, Type, PublicationDate) values (120, 'Whispers in the Celestial Embrace', 'Biography', '1923-12-13');
insert into Books (BookID, Name, Type, PublicationDate) values (121, 'The Ephemeral Odyssey', 'Science Book', '1948-07-25');
insert into Books (BookID, Name, Type, PublicationDate) values (122, 'The Enchanted Glyphs of Time', 'Science Book', '2003-09-16');
insert into Books (BookID, Name, Type, PublicationDate) values (123, 'Shadows in the Whispering Pines', 'Science Book', '1939-03-28');
insert into Books (BookID, Name, Type, PublicationDate) values (124, 'The Celestial Waltz of Eternity', 'Art Book', '2009-01-12');
insert into Books (BookID, Name, Type, PublicationDate) values (125, 'Ephemeral Echoes of the Forgotten', 'Literary Book', '2021-03-04');
insert into Books (BookID, Name, Type, PublicationDate) values (126, 'Moonlit Serenade of the Cosmos', 'Art Book', '1975-03-13');
insert into Books (BookID, Name, Type, PublicationDate) values (127, 'The Celestial Odyssey of Dreams', 'Biography', '1940-12-10');
insert into Books (BookID, Name, Type, PublicationDate) values (128, 'The Ethereal Echo of Lost Realms', 'Biography', '1934-04-03');
insert into Books (BookID, Name, Type, PublicationDate) values (129, 'Crimson Veil of Astral Whispers', 'Science Book', '2021-02-16');
insert into Books (BookID, Name, Type, PublicationDate) values (130, 'Lullaby of the Celestial Seraph', 'Literary Book', '2020-01-22');
insert into Books (BookID, Name, Type, PublicationDate) values (131, 'Sapphire Labyrinth of Lost Memories', 'Art Book', '1910-09-14');
insert into Books (BookID, Name, Type, PublicationDate) values (132, 'Ethereal Harmony of the Cosmos', 'Technical Book', '1973-03-20');
insert into Books (BookID, Name, Type, PublicationDate) values (133, 'Cascading Stardust Symphony', 'Literary Book', '1914-09-17');
insert into Books (BookID, Name, Type, PublicationDate) values (134, 'Chalice of the Celestial Alchemist', 'Science Book', '2001-08-10');
insert into Books (BookID, Name, Type, PublicationDate) values (135, 'Chronicles of the Astral Nomad', 'Art Book', '1978-12-10');
insert into Books (BookID, Name, Type, PublicationDate) values (136, 'Ephemeral Enchantments', 'Art Book', '2004-12-20');
insert into Books (BookID, Name, Type, PublicationDate) values (137, 'The Celestial Ballad of Lost Souls', 'Technical Book', '1962-11-20');
insert into Books (BookID, Name, Type, PublicationDate) values (138, 'Specters in the Astral Mist', 'Literary Book', '2020-10-19');
insert into Books (BookID, Name, Type, PublicationDate) values (139, 'Labyrinth of the Whispering Cosmos', 'Biography', '1985-12-02');
insert into Books (BookID, Name, Type, PublicationDate) values (140, 'Crimson Dreams of the Celestial Realm', 'Art Book', '1991-12-20');
insert into Books (BookID, Name, Type, PublicationDate) values (141, 'Eternal Echoes of the Forgotten Tome', 'Science Book', '2018-05-20');
insert into Books (BookID, Name, Type, PublicationDate) values (142, 'Whispers from the Astral Sanctuary', 'Technical Book', '1964-03-03');
insert into Books (BookID, Name, Type, PublicationDate) values (143, 'The Ethereal Grimoire of the Stars', 'Literary Book', '2020-10-28');
insert into Books (BookID, Name, Type, PublicationDate) values (144, 'Luminous Threads of the Celestial Tapestry', 'Art Book', '2011-07-27');
insert into Books (BookID, Name, Type, PublicationDate) values (145, 'Chorus of the Astral Muse', 'Art Book', '1989-05-08');
insert into Books (BookID, Name, Type, PublicationDate) values (146, 'The Ephemeral Whispers of the Starlight', 'Technical Book', '1916-07-25');
insert into Books (BookID, Name, Type, PublicationDate) values (147, 'Harmony of the Celestial Spheres', 'Literary Book', '1910-05-09');
insert into Books (BookID, Name, Type, PublicationDate) values (148, 'Astral Lullaby in Sapphire', 'Biography', '2016-03-21');
insert into Books (BookID, Name, Type, PublicationDate) values (149, 'Whispers Across the Cosmic Veil', 'Biography', '1960-09-24');
insert into Books (BookID, Name, Type, PublicationDate) values (150, 'Symphony of the Astral Serenade', 'Literary Book', '1938-07-09');
insert into Books (BookID, Name, Type, PublicationDate) values (151, 'Chronicles of the Celestial Voyager', 'Biography', '1963-09-07');
insert into Books (BookID, Name, Type, PublicationDate) values (152, 'Labyrinth of Celestial Whispers', 'Art Book', '1919-07-31');
insert into Books (BookID, Name, Type, PublicationDate) values (153, 'Sorcerer''s Waltz in Starlight', 'Science Book', '1959-06-13');
insert into Books (BookID, Name, Type, PublicationDate) values (154, 'Eternal Echoes of the Celestial Codex', 'Science Book', '2004-07-17');
insert into Books (BookID, Name, Type, PublicationDate) values (155, 'Sapphire Dreams of the Ethereal Muse', 'Science Book', '1970-12-16');
insert into Books (BookID, Name, Type, PublicationDate) values (156, 'The Enchanted Dance of Cosmic Shadows', 'Art Book', '1923-04-27');
insert into Books (BookID, Name, Type, PublicationDate) values (157, 'Chronicles of the Celestial Drifter', 'Technical Book', '1990-07-16');
insert into Books (BookID, Name, Type, PublicationDate) values (158, 'Astral Sonata of the Lost Realm', 'Art Book', '1954-06-04');
insert into Books (BookID, Name, Type, PublicationDate) values (159, 'Ephemeral Whispers in the Cosmic Breeze', 'Technical Book', '1928-09-01');
insert into Books (BookID, Name, Type, PublicationDate) values (160, 'Celestial Labyrinth of Forgotten Hymns', 'Technical Book', '2022-08-12');
insert into Books (BookID, Name, Type, PublicationDate) values (161, 'The Ethereal Garden of Starlight Melodies', 'Science Book', '1925-07-03');
insert into Books (BookID, Name, Type, PublicationDate) values (162, 'Crimson Echoes in the Celestial Abyss', 'Biography', '1996-05-28');
insert into Books (BookID, Name, Type, PublicationDate) values (163, 'Sorcerer''s Spellbook of Lost Realms', 'Technical Book', '2001-05-04');
insert into Books (BookID, Name, Type, PublicationDate) values (164, 'Ephemeral Whispers of the Ethereal Tome', 'Science Book', '1959-06-05');
insert into Books (BookID, Name, Type, PublicationDate) values (165, 'Celestial Sirens in Sapphire Echoes', 'Biography', '1957-10-29');
insert into Books (BookID, Name, Type, PublicationDate) values (166, 'Labyrinth of the Astral Wanderer''s Dreams', 'Technical Book', '1974-09-26');
insert into Books (BookID, Name, Type, PublicationDate) values (167, 'Eternal Echoes in the Cosmic Symphony', 'Art Book', '1981-03-04');
insert into Books (BookID, Name, Type, PublicationDate) values (168, 'Chalice of Celestial Enchantments', 'Biography', '1994-02-02');
insert into Books (BookID, Name, Type, PublicationDate) values (169, 'Whispers of the Forgotten Constellation', 'Art Book', '1908-11-04');
insert into Books (BookID, Name, Type, PublicationDate) values (170, 'Chronicles of the Celestial Minstrel', 'Technical Book', '1956-04-01');
insert into Books (BookID, Name, Type, PublicationDate) values (171, 'Crimson Veil of Astral Enchantments', 'Biography', '1957-10-29');
insert into Books (BookID, Name, Type, PublicationDate) values (172, 'The Ethereal Lullaby of Celestial Hopes', 'Science Book', '1959-06-29');
insert into Books (BookID, Name, Type, PublicationDate) values (173, 'Sorcerer''s Symphony of Lost Echoes', 'Literary Book', '1988-04-17');
insert into Books (BookID, Name, Type, PublicationDate) values (174, 'Ephemeral Whispers in the Astral Garden', 'Science Book', '1902-10-26');
insert into Books (BookID, Name, Type, PublicationDate) values (175, 'The Celestial Waltz of Eternal Dreams', 'Biography', '1903-11-28');
insert into Books (BookID, Name, Type, PublicationDate) values (176, 'To Silence a Nightingale', 'Art Book', '1963-08-17');
insert into Books (BookID, Name, Type, PublicationDate) values (177, '2077', 'Art Book', '1958-10-20');
insert into Books (BookID, Name, Type, PublicationDate) values (178, 'The Grand Gala', 'Biography', '1906-08-25');
insert into Books (BookID, Name, Type, PublicationDate) values (179, 'Dignity and Bias', 'Literary Book', '1987-11-30');
insert into Books (BookID, Name, Type, PublicationDate) values (180, 'The Seeker in the Wheatfield', 'Biography', '1927-10-07');
insert into Books (BookID, Name, Type, PublicationDate) values (181, 'Wizards and Wonders: The Alchemist''s Initiation', 'Technical Book', '1933-11-02');
insert into Books (BookID, Name, Type, PublicationDate) values (182, 'The Sovereign of the Bands', 'Art Book', '2016-08-08');
insert into Books (BookID, Name, Type, PublicationDate) values (183, 'The Enchanted Mirror', 'Biography', '1968-12-05');
insert into Books (BookID, Name, Type, PublicationDate) values (184, 'Echoes of a Forgotten Sonata', 'Technical Book', '1943-12-16');
insert into Books (BookID, Name, Type, PublicationDate) values (185, 'Midnight Masquerade', 'Art Book', '1961-06-28');
insert into Books (BookID, Name, Type, PublicationDate) values (186, 'Specters in the Shadows', 'Literary Book', '1937-05-09');
insert into Books (BookID, Name, Type, PublicationDate) values (187, 'The Celestial Alchemy Codex', 'Technical Book', '1967-06-04');
insert into Books (BookID, Name, Type, PublicationDate) values (188, 'Whispers in the Misty Grove', 'Biography', '1953-05-09');
insert into Books (BookID, Name, Type, PublicationDate) values (189, 'Secrets of the Astral Nomad', 'Biography', '1946-07-30');
insert into Books (BookID, Name, Type, PublicationDate) values (190, 'Aetherial Lullaby', 'Literary Book', '1926-04-05');
insert into Books (BookID, Name, Type, PublicationDate) values (191, 'The Forgotten Enigma', 'Science Book', '1948-11-04');
insert into Books (BookID, Name, Type, PublicationDate) values (192, 'Harmony in the Hidden Garden', 'Art Book', '2002-07-10');
insert into Books (BookID, Name, Type, PublicationDate) values (193, 'Legends of the Starlit Realm', 'Technical Book', '1974-07-11');
insert into Books (BookID, Name, Type, PublicationDate) values (194, 'Crimson Dreams of the Ethereal Muse', 'Biography', '1909-08-28');
insert into Books (BookID, Name, Type, PublicationDate) values (195, 'Whispers of the Forgotten Constellation', 'Biography', '1959-09-27');
insert into Books (BookID, Name, Type, PublicationDate) values (196, 'Chronicles of the Celestial Minstrel', 'Science Book', '1951-05-30');
insert into Books (BookID, Name, Type, PublicationDate) values (197, 'Celestial Sirens in Sapphire', 'Science Book', '1997-08-12');
insert into Books (BookID, Name, Type, PublicationDate) values (198, 'Echoes of the Celestial Abyss', 'Biography', '1969-10-30');
insert into Books (BookID, Name, Type, PublicationDate) values (199, 'Sorcerer''s Spellbook of Enchanted Realms', 'Literary Book', '1928-11-27');
insert into Books (BookID, Name, Type, PublicationDate) values (200, 'Ephemeral Whispers in the Astral Garden', 'Literary Book', '2007-05-26');
insert into Books (BookID, Name, Type, PublicationDate) values (201, 'The Celestial Waltz of Eternal Dreams', 'Biography', '1927-11-11');
insert into Books (BookID, Name, Type, PublicationDate) values (202, 'Whispers of the Starborn Serenade', 'Biography', '1987-09-08');
insert into Books (BookID, Name, Type, PublicationDate) values (203, 'Chronicles of the Cosmic Voyager', 'Literary Book', '1929-10-03');
insert into Books (BookID, Name, Type, PublicationDate) values (204, 'Labyrinth of Celestial Whispers', 'Literary Book', '1925-10-10');
insert into Books (BookID, Name, Type, PublicationDate) values (205, 'Astral Sonata of the Lost Realm', 'Science Book', '1902-11-06');
insert into Books (BookID, Name, Type, PublicationDate) values (206, 'Ephemeral Whispers in the Cosmic Breeze', 'Science Book', '2003-11-29');
insert into Books (BookID, Name, Type, PublicationDate) values (207, 'Celestial Labyrinth of Forgotten Hymns', 'Technical Book', '1911-10-07');
insert into Books (BookID, Name, Type, PublicationDate) values (208, 'The Ethereal Garden of Starlight Melodies', 'Literary Book', '1930-12-24');
insert into Books (BookID, Name, Type, PublicationDate) values (209, 'Crimson Echoes in the Celestial Abyss', 'Art Book', '1960-09-25');
insert into Books (BookID, Name, Type, PublicationDate) values (210, 'Sorcerer''s Symphony of Lost Echoes', 'Art Book', '1974-11-27');
insert into Books (BookID, Name, Type, PublicationDate) values (211, 'Ephemeral Whispers in the Ethereal Tome', 'Literary Book', '2006-08-24');
insert into Books (BookID, Name, Type, PublicationDate) values (212, 'Celestial Sirens in Sapphire Echoes', 'Literary Book', '1922-08-22');
insert into Books (BookID, Name, Type, PublicationDate) values (213, 'Labyrinth of the Astral Wanderer''s Dreams', 'Science Book', '1969-11-26');
insert into Books (BookID, Name, Type, PublicationDate) values (214, 'Eternal Echoes in the Cosmic Symphony', 'Art Book', '2017-02-08');
insert into Books (BookID, Name, Type, PublicationDate) values (215, 'Chalice of Celestial Enchantments', 'Literary Book', '1942-07-24');
insert into Books (BookID, Name, Type, PublicationDate) values (216, 'Whispers of the Forgotten Constellation', 'Biography', '1945-09-26');
insert into Books (BookID, Name, Type, PublicationDate) values (217, 'Chronicles of the Celestial Minstrel', 'Biography', '1945-09-09');
insert into Books (BookID, Name, Type, PublicationDate) values (218, 'Crimson Veil of Astral Enchantments', 'Biography', '1933-07-12');
insert into Books (BookID, Name, Type, PublicationDate) values (219, 'The Ethereal Lullaby of Celestial Hopes', 'Science Book', '2001-04-06');
insert into Books (BookID, Name, Type, PublicationDate) values (220, 'Sorcerer''s Symphony of Lost Echoes', 'Art Book', '1999-09-25');
insert into Books (BookID, Name, Type, PublicationDate) values (221, 'Ephemeral Whispers in the Astral Garden', 'Technical Book', '1980-04-20');
insert into Books (BookID, Name, Type, PublicationDate) values (222, 'The Celestial Waltz of Eternal Dreams', 'Technical Book', '1951-05-02');
insert into Books (BookID, Name, Type, PublicationDate) values (223, 'Whispers of the Starborn Serenade', 'Technical Book', '1991-01-08');
insert into Books (BookID, Name, Type, PublicationDate) values (224, 'Chronicles of the Cosmic Voyager', 'Science Book', '1994-04-20');
insert into Books (BookID, Name, Type, PublicationDate) values (225, 'Labyrinth of Celestial Whispers', 'Art Book', '1913-11-27');
insert into Books (BookID, Name, Type, PublicationDate) values (226, 'Astral Sonata of the Lost Realm', 'Science Book', '1921-01-13');
insert into Books (BookID, Name, Type, PublicationDate) values (227, 'Ephemeral Whispers in the Cosmic Breeze', 'Literary Book', '2009-04-14');
insert into Books (BookID, Name, Type, PublicationDate) values (228, 'Celestial Labyrinth of Forgotten Hymns', 'Art Book', '2006-10-07');
insert into Books (BookID, Name, Type, PublicationDate) values (229, 'The Ethereal Garden of Starlight Melodies', 'Biography', '1973-06-16');
insert into Books (BookID, Name, Type, PublicationDate) values (230, 'Crimson Echoes in the Celestial Abyss', 'Biography', '2016-01-30');
insert into Books (BookID, Name, Type, PublicationDate) values (231, 'Sorcerer''s Spellbook of Enchanted Realms', 'Literary Book', '1957-09-08');
insert into Books (BookID, Name, Type, PublicationDate) values (232, 'Ephemeral Whispers in the Astral Garden', 'Science Book', '1932-05-11');
insert into Books (BookID, Name, Type, PublicationDate) values (233, 'The Celestial Waltz of Eternal Dreams', 'Biography', '1969-07-27');
insert into Books (BookID, Name, Type, PublicationDate) values (234, 'Whispers of the Starborn Serenade', 'Science Book', '1963-04-02');
insert into Books (BookID, Name, Type, PublicationDate) values (235, 'Chronicles of the Cosmic Voyager', 'Technical Book', '1965-09-01');
insert into Books (BookID, Name, Type, PublicationDate) values (236, 'Labyrinth of Celestial Whispers', 'Science Book', '1981-03-14');
insert into Books (BookID, Name, Type, PublicationDate) values (237, 'Astral Sonata of the Lost Realm', 'Literary Book', '1942-03-07');
insert into Books (BookID, Name, Type, PublicationDate) values (238, 'Ephemeral Whispers in the Cosmic Breeze', 'Biography', '1964-04-27');
insert into Books (BookID, Name, Type, PublicationDate) values (239, 'Celestial Labyrinth of Forgotten Hymns', 'Biography', '2017-05-09');
insert into Books (BookID, Name, Type, PublicationDate) values (240, 'The Ethereal Garden of Starlight Melodies', 'Biography', '1925-05-11');
insert into Books (BookID, Name, Type, PublicationDate) values (241, 'Crimson Echoes in the Celestial Abyss', 'Biography', '1936-03-21');
insert into Books (BookID, Name, Type, PublicationDate) values (242, 'Sorcerer''s Symphony of Lost Echoes', 'Biography', '1984-01-30');
insert into Books (BookID, Name, Type, PublicationDate) values (243, 'Ephemeral Whispers in the Ethereal Tome', 'Technical Book', '1903-08-30');
insert into Books (BookID, Name, Type, PublicationDate) values (244, 'Celestial Sirens in Sapphire Echoes', 'Art Book', '1908-06-09');
insert into Books (BookID, Name, Type, PublicationDate) values (245, 'Labyrinth of the Astral Wanderer''s Dreams', 'Literary Book', '1929-09-28');
insert into Books (BookID, Name, Type, PublicationDate) values (246, 'Eternal Echoes in the Cosmic Symphony', 'Technical Book', '1966-10-03');
insert into Books (BookID, Name, Type, PublicationDate) values (247, 'Chalice of Celestial Enchantments', 'Art Book', '2018-02-03');
insert into Books (BookID, Name, Type, PublicationDate) values (248, 'Whispers of the Forgotten Constellation', 'Technical Book', '1953-03-08');
insert into Books (BookID, Name, Type, PublicationDate) values (249, 'Chronicles of the Celestial Minstrel', 'Biography', '1943-01-28');
insert into Books (BookID, Name, Type, PublicationDate) values (250, 'Crimson Veil of Astral Enchantments', 'Science Book', '1940-12-16');
insert into Books (BookID, Name, Type, PublicationDate) values (251, 'The Ethereal Lullaby of Celestial Hopes', 'Literary Book', '1969-04-22');
insert into Books (BookID, Name, Type, PublicationDate) values (252, '1200', 'Science Book', '1918-03-02');
insert into Books (BookID, Name, Type, PublicationDate) values (253, 'Story of Jane', 'Technical Book', '2008-03-07');
insert into Books (BookID, Name, Type, PublicationDate) values (254, 'E!', 'Technical Book', '1905-04-04');
insert into Books (BookID, Name, Type, PublicationDate) values (255, 'House', 'Biography', '1929-09-23');
insert into Books (BookID, Name, Type, PublicationDate) values (256, 'Where is the Love', 'Biography', '1984-01-08');
insert into Books (BookID, Name, Type, PublicationDate) values (257, 'How do you know', 'Literary Book', '1993-05-29');
insert into Books (BookID, Name, Type, PublicationDate) values (258, 'Flowers', 'Science Book', '1926-09-12');
insert into Books (BookID, Name, Type, PublicationDate) values (259, '1999', 'Science Book', '1995-06-22');
insert into Books (BookID, Name, Type, PublicationDate) values (260, '1991', 'Art Book', '1933-08-30');
insert into Books (BookID, Name, Type, PublicationDate) values (261, 'The Enigmatic Echoes of Forgotten Whispers', 'Technical Book', '1967-06-16');
insert into Books (BookID, Name, Type, PublicationDate) values (262, 'Mysteries in the Celestial Garden', 'Biography', '1945-02-25');
insert into Books (BookID, Name, Type, PublicationDate) values (263, 'Specters of the Cosmic Tapestry', 'Biography', '1912-11-16');
insert into Books (BookID, Name, Type, PublicationDate) values (264, 'The Ethereal Nocturne', 'Technical Book', '1997-12-11');
insert into Books (BookID, Name, Type, PublicationDate) values (265, 'Astral Chronicles of the Moonlit Realm', 'Science Book', '1958-10-13');
insert into Books (BookID, Name, Type, PublicationDate) values (266, 'Crimson Veil of Timeless Dreams', 'Technical Book', '1967-01-14');
insert into Books (BookID, Name, Type, PublicationDate) values (267, 'Songs of the Celestial Muse', 'Art Book', '1957-09-21');
insert into Books (BookID, Name, Type, PublicationDate) values (268, 'The Enchanted Alchemy of Stardust', 'Technical Book', '2003-03-16');
insert into Books (BookID, Name, Type, PublicationDate) values (269, 'Whispers Across the Nebula', 'Biography', '2014-08-24');
insert into Books (BookID, Name, Type, PublicationDate) values (270, 'Celestial Lullabies in Sapphire', 'Art Book', '2008-03-08');
insert into Books (BookID, Name, Type, PublicationDate) values (271, 'Ephemeral Dreams of the Starlit Nomad', 'Art Book', '1984-09-04');
insert into Books (BookID, Name, Type, PublicationDate) values (272, 'Sorcerer''s Symphony in Time', 'Literary Book', '1914-03-11');
insert into Books (BookID, Name, Type, PublicationDate) values (273, 'The Celestial Odyssey of Whispered Realms', 'Literary Book', '1930-08-23');
insert into Books (BookID, Name, Type, PublicationDate) values (274, 'Echoes from the Forgotten Galaxy', 'Literary Book', '2007-06-03');
insert into Books (BookID, Name, Type, PublicationDate) values (275, 'Crimson Sirens of the Celestial Wind', 'Art Book', '1937-04-11');
insert into Books (BookID, Name, Type, PublicationDate) values (276, 'Astral Spells and Enchanted Portals', 'Art Book', '1913-02-19');
insert into Books (BookID, Name, Type, PublicationDate) values (277, 'The Ethereal Dance of Astral Shadows', 'Science Book', '1970-10-02');
insert into Books (BookID, Name, Type, PublicationDate) values (278, 'Sorcerer''s Soliloquy in Starlight', 'Art Book', '1927-01-21');
insert into Books (BookID, Name, Type, PublicationDate) values (279, 'Ephemeral Whispers in the Celestial Abyss', 'Literary Book', '2017-06-02');
insert into Books (BookID, Name, Type, PublicationDate) values (280, 'The Starborn Serenade of Eternity', 'Biography', '1941-09-06');
insert into Books (BookID, Name, Type, PublicationDate) values (281, 'Chronicles of the Nebula''s Embrace', 'Literary Book', '2008-02-19');
insert into Books (BookID, Name, Type, PublicationDate) values (282, 'Astral Dreams in the Sapphire Sky', 'Science Book', '1911-04-15');
insert into Books (BookID, Name, Type, PublicationDate) values (283, 'Whispers of the Enchanted Nomad', 'Biography', '1983-01-23');
insert into Books (BookID, Name, Type, PublicationDate) values (284, 'The Celestial Waltz of Shifting Realms', 'Technical Book', '1922-01-20');
insert into Books (BookID, Name, Type, PublicationDate) values (285, 'Echoes of the Astral Symphony', 'Literary Book', '1922-02-20');
insert into Books (BookID, Name, Type, PublicationDate) values (286, 'Crimson Portals of Celestial Enchantment', 'Literary Book', '1967-10-19');
insert into Books (BookID, Name, Type, PublicationDate) values (287, 'Astral Labyrinth of Whispers', 'Art Book', '2003-03-01');
insert into Books (BookID, Name, Type, PublicationDate) values (288, 'Sorcerer''s Sonata in Sapphire', 'Science Book', '1988-05-01');
insert into Books (BookID, Name, Type, PublicationDate) values (289, 'Ephemeral Whispers of the Celestial Codex', 'Literary Book', '1904-09-24');
insert into Books (BookID, Name, Type, PublicationDate) values (290, 'The Ethereal Rhapsody of Forgotten Stars', 'Technical Book', '2003-05-29');
insert into Books (BookID, Name, Type, PublicationDate) values (291, 'Celestial Nocturnes in Crimson', 'Biography', '1962-08-16');
insert into Books (BookID, Name, Type, PublicationDate) values (292, 'Labyrinth of Stardust and Echoes', 'Art Book', '1954-08-26');
insert into Books (BookID, Name, Type, PublicationDate) values (293, 'The Enchanted Harmony of Celestial Realms', 'Technical Book', '1969-02-07');
insert into Books (BookID, Name, Type, PublicationDate) values (294, 'Whispers of the Ephemeral Lullaby', 'Literary Book', '1970-08-01');
insert into Books (BookID, Name, Type, PublicationDate) values (295, 'Chronicles of the Astral Nomad''s Journey', 'Literary Book', '1993-01-27');
insert into Books (BookID, Name, Type, PublicationDate) values (296, 'Astral Tapestry of Celestial Whispers', 'Technical Book', '1922-12-13');
insert into Books (BookID, Name, Type, PublicationDate) values (297, 'Crimson Echoes of the Enchanted Realm', 'Literary Book', '1982-12-29');
insert into Books (BookID, Name, Type, PublicationDate) values (298, 'Sorcerer''s Spellbook of Celestial Dreams', 'Technical Book', '1946-12-16');
insert into Books (BookID, Name, Type, PublicationDate) values (299, 'Ephemeral Whispers in the Ethereal Garden', 'Biography', '2006-06-19');
insert into Books (BookID, Name, Type, PublicationDate) values (300, 'The Celestial Ballad of Enchanted Hopes', 'Science Book', '2005-02-09');
insert into Books (BookID, Name, Type, PublicationDate) values (301, 'Songs of the Forgotten Nebula', 'Art Book', '1922-05-25');
insert into Books (BookID, Name, Type, PublicationDate) values (302, 'The Ethereal Waltz of Cosmic Echoes', 'Art Book', '2012-07-14');
insert into Books (BookID, Name, Type, PublicationDate) values (303, 'Crimson Serenade of Astral Dreams', 'Literary Book', '1949-07-11');
insert into Books (BookID, Name, Type, PublicationDate) values (304, 'Astral Sirens in the Enchanted Mist', 'Art Book', '1960-07-02');
insert into Books (BookID, Name, Type, PublicationDate) values (305, 'Echoes of the Celestial Minstrel', 'Literary Book', '1986-06-25');
insert into Books (BookID, Name, Type, PublicationDate) values (306, 'Chronicles of the Forgotten Galaxy', 'Biography', '2014-11-14');
insert into Books (BookID, Name, Type, PublicationDate) values (307, 'The Enchanted Alchemy of Celestial Dust', 'Art Book', '2010-10-02');
insert into Books (BookID, Name, Type, PublicationDate) values (308, 'Whispers Across the Astral Sea', 'Biography', '1966-06-28');
insert into Books (BookID, Name, Type, PublicationDate) values (309, 'Celestial Lullabies in Sapphire Harmony', 'Technical Book', '1937-08-29');
insert into Books (BookID, Name, Type, PublicationDate) values (310, 'Ephemeral Dreams of the Starlit Voyager', 'Technical Book', '1921-10-13');
insert into Books (BookID, Name, Type, PublicationDate) values (311, 'Sorcerer''s Symphony in Eternity', 'Science Book', '1941-12-31');
insert into Books (BookID, Name, Type, PublicationDate) values (312, 'The Celestial Odyssey of Shifting Realms', 'Technical Book', '2015-07-07');
insert into Books (BookID, Name, Type, PublicationDate) values (313, 'Echoes from the Astral Garden', 'Literary Book', '1902-08-18');
insert into Books (BookID, Name, Type, PublicationDate) values (314, 'Crimson Sirens of the Celestial Symphony', 'Technical Book', '1918-02-04');
insert into Books (BookID, Name, Type, PublicationDate) values (315, 'Astral Spells and Enchanted Echoes', 'Technical Book', '1976-12-31');
insert into Books (BookID, Name, Type, PublicationDate) values (316, 'The Ethereal Dance of Stardust and Shadows', 'Technical Book', '2013-12-26');
insert into Books (BookID, Name, Type, PublicationDate) values (317, 'Sorcerer''s Soliloquy in Celestial Time', 'Technical Book', '1908-07-10');
insert into Books (BookID, Name, Type, PublicationDate) values (318, 'Ephemeral Whispers in the Sapphire Sky', 'Biography', '1949-07-16');
insert into Books (BookID, Name, Type, PublicationDate) values (319, 'The Starborn Serenade of Whispered Realms', 'Art Book', '2014-09-07');
insert into Books (BookID, Name, Type, PublicationDate) values (320, 'Chronicles of the Nebula''s Enchantment', 'Science Book', '1910-06-19');
insert into Books (BookID, Name, Type, PublicationDate) values (321, 'Astral Dreams in the Enchanted Nocturne', 'Art Book', '1901-03-16');
insert into Books (BookID, Name, Type, PublicationDate) values (322, 'Whispers of the Celestial Alchemist', 'Science Book', '2006-11-30');
insert into Books (BookID, Name, Type, PublicationDate) values (323, 'The Celestial Waltz of Forgotten Echoes', 'Technical Book', '1932-01-04');
insert into Books (BookID, Name, Type, PublicationDate) values (324, 'Echoes of the Astral Spellbook', 'Art Book', '1961-12-02');
insert into Books (BookID, Name, Type, PublicationDate) values (325, 'Crimson Portals of Celestial Dreams', 'Literary Book', '1962-07-27');
insert into Books (BookID, Name, Type, PublicationDate) values (326, 'Astral Labyrinth of Enchanted Whispers', 'Art Book', '2003-11-02');
insert into Books (BookID, Name, Type, PublicationDate) values (327, 'Sorcerer''s Sonata in Celestial Harmony', 'Biography', '1918-08-07');
insert into Books (BookID, Name, Type, PublicationDate) values (328, 'Ephemeral Whispers of the Nebula''s Embrace', 'Biography', '1926-10-27');
insert into Books (BookID, Name, Type, PublicationDate) values (329, 'The Ethereal Rhapsody of Celestial Shadows', 'Technical Book', '1937-08-24');
insert into Books (BookID, Name, Type, PublicationDate) values (330, 'Celestial Nocturnes in Forgotten Dreams', 'Art Book', '1960-12-27');
insert into Books (BookID, Name, Type, PublicationDate) values (331, 'Labyrinth of Stardust and Celestial Portals', 'Art Book', '2001-04-20');
insert into Books (BookID, Name, Type, PublicationDate) values (332, 'The Enchanted Harmony of Astral Echoes', 'Literary Book', '1922-10-12');
insert into Books (BookID, Name, Type, PublicationDate) values (333, 'Whispers of the Ephemeral Celestial Symphony', 'Literary Book', '1991-08-06');
insert into Books (BookID, Name, Type, PublicationDate) values (334, 'Chronicles of the Celestial Voyager''s Journey', 'Technical Book', '2000-05-01');
insert into Books (BookID, Name, Type, PublicationDate) values (335, 'Astral Tapestry of Whispered Realms', 'Technical Book', '1902-11-16');
insert into Books (BookID, Name, Type, PublicationDate) values (336, 'Crimson Echoes of the Enchanted Symphony', 'Science Book', '1969-10-22');
insert into Books (BookID, Name, Type, PublicationDate) values (337, 'Sorcerer''s Spellbook of Celestial Dreams', 'Literary Book', '1933-02-09');
insert into Books (BookID, Name, Type, PublicationDate) values (338, 'Ephemeral Whispers in the Enchanted Garden', 'Art Book', '1956-02-16');
insert into Books (BookID, Name, Type, PublicationDate) values (339, 'The Celestial Ballad of Stardust and Echoes', 'Technical Book', '1943-09-18');
insert into Books (BookID, Name, Type, PublicationDate) values (340, 'Songs of the Forgotten Astral Sea', 'Biography', '1964-05-19');
insert into Books (BookID, Name, Type, PublicationDate) values (341, 'The Ethereal Waltz of Celestial Whispers', 'Biography', '1974-10-15');
insert into Books (BookID, Name, Type, PublicationDate) values (342, 'Crimson Serenade of Stardust Dreams', 'Art Book', '1951-01-10');
insert into Books (BookID, Name, Type, PublicationDate) values (343, 'Astral Sirens in the Celestial Mist', 'Art Book', '1911-10-03');
insert into Books (BookID, Name, Type, PublicationDate) values (344, 'Echoes of the Celestial Minstrel''s Lullaby', 'Technical Book', '2004-11-07');
insert into Books (BookID, Name, Type, PublicationDate) values (345, 'Chronicles of the Forgotten Astral Realm', 'Literary Book', '2011-10-15');
insert into Books (BookID, Name, Type, PublicationDate) values (346, 'The Enchanted Alchemy of Celestial Dreams', 'Art Book', '1972-02-14');
insert into Books (BookID, Name, Type, PublicationDate) values (347, 'Whispers Across the Stardust Sea', 'Biography', '1989-07-21');
insert into Books (BookID, Name, Type, PublicationDate) values (348, 'Celestial Lullabies in Crimson Harmony', 'Science Book', '1987-09-19');
insert into Books (BookID, Name, Type, PublicationDate) values (349, 'Ephemeral Dreams of the Celestial Voyager', 'Art Book', '1903-12-15');
insert into Books (BookID, Name, Type, PublicationDate) values (350, 'Sorcerer''s Symphony in Shifting Realms', 'Art Book', '1925-12-08');
insert into Books (BookID, Name, Type, PublicationDate) values (351, 'The Celestial Odyssey of Astral Echoes', 'Technical Book', '2008-09-09');
insert into Books (BookID, Name, Type, PublicationDate) values (352, 'Echoes from the Celestial Garden', 'Biography', '2020-10-04');
insert into Books (BookID, Name, Type, PublicationDate) values (353, 'Crimson Sirens of the Enchanted Symphony', 'Art Book', '1978-09-09');
insert into Books (BookID, Name, Type, PublicationDate) values (354, 'Astral Spells and Celestial Echoes', 'Technical Book', '1968-09-30');
insert into Books (BookID, Name, Type, PublicationDate) values (355, 'The Ethereal Dance of Forgotten Dreams', 'Biography', '1951-03-21');
insert into Books (BookID, Name, Type, PublicationDate) values (356, 'Sorcerer''s Soliloquy in Celestial Harmony', 'Biography', '1938-07-12');
insert into Books (BookID, Name, Type, PublicationDate) values (357, 'Ephemeral Whispers in the Astral Sky', 'Biography', '1981-09-20');
insert into Books (BookID, Name, Type, PublicationDate) values (358, 'The Starborn Serenade of Stardust Realms', 'Biography', '1915-10-09');
insert into Books (BookID, Name, Type, PublicationDate) values (359, 'Chronicles of the Nebula''s Celestial Enchantment', 'Art Book', '1910-10-31');
insert into Books (BookID, Name, Type, PublicationDate) values (360, 'Astral Dreams in the Forgotten Nocturne', 'Biography', '2022-07-24');
insert into Books (BookID, Name, Type, PublicationDate) values (361, 'Whispers of the Celestial Alchemist''s Garden', 'Technical Book', '1967-07-17');
insert into Books (BookID, Name, Type, PublicationDate) values (362, 'The Celestial Waltz of Enchanted Echoes', 'Literary Book', '1977-07-07');
insert into Books (BookID, Name, Type, PublicationDate) values (363, 'Echoes of the Astral Spellbook''s Symphony', 'Art Book', '2015-05-21');
insert into Books (BookID, Name, Type, PublicationDate) values (364, 'Crimson Portals of Stardust Dreams', 'Science Book', '1927-02-27');
insert into Books (BookID, Name, Type, PublicationDate) values (365, 'Astral Labyrinth of Celestial Whispers', 'Science Book', '1950-04-11');
insert into Books (BookID, Name, Type, PublicationDate) values (366, 'Sorcerer''s Sonata in Enchanted Harmony', 'Biography', '1914-06-11');
insert into Books (BookID, Name, Type, PublicationDate) values (367, 'Ephemeral Whispers of the Celestial Embrace', 'Biography', '1906-05-14');
insert into Books (BookID, Name, Type, PublicationDate) values (368, 'The Ethereal Rhapsody of Astral Shadows', 'Biography', '1962-06-10');
insert into Books (BookID, Name, Type, PublicationDate) values (369, 'Celestial Nocturnes in Stardust Dreams', 'Science Book', '2001-01-14');
insert into Books (BookID, Name, Type, PublicationDate) values (370, 'Labyrinth of Astral Echoes and Portals', 'Biography', '1953-10-29');
insert into Books (BookID, Name, Type, PublicationDate) values (371, 'The Enchanted Harmony of Celestial Shadows', 'Science Book', '1903-12-01');
insert into Books (BookID, Name, Type, PublicationDate) values (372, 'Whispers of the Ephemeral Astral Symphony', 'Literary Book', '1982-08-12');
insert into Books (BookID, Name, Type, PublicationDate) values (373, 'Chronicles of the Celestial Voyager''s Odyssey', 'Biography', '1927-02-22');
insert into Books (BookID, Name, Type, PublicationDate) values (374, 'Astral Tapestry of Stardust and Echoes', 'Technical Book', '1968-11-24');
insert into Books (BookID, Name, Type, PublicationDate) values (375, 'Crimson Echoes of the Celestial Symphony', 'Technical Book', '1990-07-30');
insert into Books (BookID, Name, Type, PublicationDate) values (376, 'Sorcerer''s Spellbook of Forgotten Dreams', 'Art Book', '1980-02-12');
insert into Books (BookID, Name, Type, PublicationDate) values (377, 'Ephemeral Whispers in the Enchanted Garden', 'Technical Book', '1910-12-06');
insert into Books (BookID, Name, Type, PublicationDate) values (378, 'The Celestial Ballad of Celestial Portals', 'Technical Book', '1960-09-02');
insert into Books (BookID, Name, Type, PublicationDate) values (379, 'Songs of the Forgotten Astral Sea', 'Technical Book', '1977-11-21');
insert into Books (BookID, Name, Type, PublicationDate) values (380, 'The Ethereal Waltz of Stardust Whispers', 'Art Book', '1909-01-27');
insert into Books (BookID, Name, Type, PublicationDate) values (381, 'Crimson Serenade of Celestial Dreams', 'Technical Book', '2007-08-27');
insert into Books (BookID, Name, Type, PublicationDate) values (382, 'Astral Sirens in the Enchanted Mist', 'Technical Book', '1927-07-15');
insert into Books (BookID, Name, Type, PublicationDate) values (383, 'Echoes of the Celestial Minstrel''s Symphony', 'Science Book', '1968-12-14');
insert into Books (BookID, Name, Type, PublicationDate) values (384, 'Chronicles of the Forgotten Astral Realm', 'Technical Book', '1917-12-01');
insert into Books (BookID, Name, Type, PublicationDate) values (385, 'The Enchanted Alchemy of Celestial Whispers', 'Art Book', '1990-05-02');
insert into Books (BookID, Name, Type, PublicationDate) values (386, 'Whispers Across the Stardust Sea', 'Technical Book', '2017-04-22');
insert into Books (BookID, Name, Type, PublicationDate) values (387, 'Celestial Lullabies in Crimson Harmony', 'Art Book', '2001-10-04');
insert into Books (BookID, Name, Type, PublicationDate) values (388, 'Ephemeral Dreams of the Celestial Voyager', 'Science Book', '2011-06-19');
insert into Books (BookID, Name, Type, PublicationDate) values (389, 'Sorcerer''s Symphony in Shifting Realms', 'Biography', '1914-07-30');
insert into Books (BookID, Name, Type, PublicationDate) values (390, 'The Celestial Odyssey of Astral Echoes', 'Technical Book', '1942-07-06');
insert into Books (BookID, Name, Type, PublicationDate) values (391, 'Echoes from the Celestial Garden', 'Literary Book', '2017-08-30');
insert into Books (BookID, Name, Type, PublicationDate) values (392, 'Crimson Sirens of the Enchanted Symphony', 'Science Book', '1987-10-10');
insert into Books (BookID, Name, Type, PublicationDate) values (393, 'Astral Spells and Celestial Echoes', 'Biography', '1962-06-08');
insert into Books (BookID, Name, Type, PublicationDate) values (394, 'The Ethereal Dance of Forgotten Dreams', 'Biography', '1945-07-09');
insert into Books (BookID, Name, Type, PublicationDate) values (395, 'Sorcerer''s Soliloquy in Celestial Harmony', 'Literary Book', '1917-04-02');
insert into Books (BookID, Name, Type, PublicationDate) values (396, 'Ephemeral Whispers in the Astral Sky', 'Science Book', '1986-08-13');
insert into Books (BookID, Name, Type, PublicationDate) values (397, 'The Starborn Serenade of Stardust Realms', 'Technical Book', '1914-12-16');
insert into Books (BookID, Name, Type, PublicationDate) values (398, 'Chronicles of the Nebula''s Celestial Enchantment', 'Literary Book', '1973-12-30');
insert into Books (BookID, Name, Type, PublicationDate) values (399, 'Astral Dreams in the Forgotten Nocturne', 'Science Book', '1996-04-28');
insert into Books (BookID, Name, Type, PublicationDate) values (400, 'Whispers of the Celestial Alchemist''s Garden', 'Art Book', '2004-06-26');
insert into Books (BookID, Name, Type, PublicationDate) values (401, 'The Celestial Waltz of Enchanted Echoes', 'Technical Book', '2020-03-18');
insert into Books (BookID, Name, Type, PublicationDate) values (402, 'Echoes of the Astral Spellbook''s Symphony', 'Technical Book', '1908-06-20');
insert into Books (BookID, Name, Type, PublicationDate) values (403, 'Crimson Portals of Stardust Dreams', 'Art Book', '2016-08-17');
insert into Books (BookID, Name, Type, PublicationDate) values (404, 'Astral Labyrinth of Celestial Whispers', 'Science Book', '1998-10-18');
insert into Books (BookID, Name, Type, PublicationDate) values (405, 'Sorcerer''s Sonata in Enchanted Harmony', 'Art Book', '1922-07-11');
insert into Books (BookID, Name, Type, PublicationDate) values (406, 'Ephemeral Whispers of the Celestial Embrace', 'Literary Book', '1933-04-06');
insert into Books (BookID, Name, Type, PublicationDate) values (407, 'The Ethereal Rhapsody of Astral Shadows', 'Technical Book', '1956-02-03');
insert into Books (BookID, Name, Type, PublicationDate) values (408, 'Celestial Nocturnes in Stardust Dreams', 'Science Book', '1952-11-16');
insert into Books (BookID, Name, Type, PublicationDate) values (409, 'Labyrinth of Astral Echoes and Portals', 'Art Book', '1992-10-08');
insert into Books (BookID, Name, Type, PublicationDate) values (410, 'The Enchanted Harmony of Celestial Shadows', 'Technical Book', '1939-10-11');
insert into Books (BookID, Name, Type, PublicationDate) values (411, 'Whispers of the Ephemeral Astral Symphony', 'Technical Book', '1965-07-21');
insert into Books (BookID, Name, Type, PublicationDate) values (412, 'Chronicles of the Celestial Voyager''s Odyssey', 'Biography', '2002-04-04');
insert into Books (BookID, Name, Type, PublicationDate) values (413, 'Astral Tapestry of Stardust and Echoes', 'Science Book', '2011-05-04');
insert into Books (BookID, Name, Type, PublicationDate) values (414, 'Crimson Echoes of the Celestial Symphony', 'Science Book', '2004-08-21');
insert into Books (BookID, Name, Type, PublicationDate) values (415, 'Sorcerer''s Spellbook of Forgotten Dreams', 'Literary Book', '1987-09-12');
insert into Books (BookID, Name, Type, PublicationDate) values (416, 'Ephemeral Whispers in the Enchanted Garden', 'Biography', '1958-07-20');
insert into Books (BookID, Name, Type, PublicationDate) values (417, 'The Celestial Ballad of Celestial Portals', 'Biography', '2019-11-23');
insert into Books (BookID, Name, Type, PublicationDate) values (418, 'Songs of the Forgotten Astral Sea', 'Biography', '1992-08-06');
insert into Books (BookID, Name, Type, PublicationDate) values (419, 'The Ethereal Waltz of Stardust Whispers', 'Science Book', '1928-06-25');
insert into Books (BookID, Name, Type, PublicationDate) values (420, 'Crimson Serenade of Celestial Dreams', 'Art Book', '1911-04-17');
insert into Books (BookID, Name, Type, PublicationDate) values (421, 'Astral Sirens in the Enchanted Mist', 'Literary Book', '1917-01-07');
insert into Books (BookID, Name, Type, PublicationDate) values (422, 'Echoes of the Celestial Minstrel''s Symphony', 'Biography', '1947-09-13');
insert into Books (BookID, Name, Type, PublicationDate) values (423, 'Chronicles of the Forgotten Astral Realm', 'Literary Book', '1944-10-15');
insert into Books (BookID, Name, Type, PublicationDate) values (424, 'The Enchanted Alchemy of Celestial Whispers', 'Literary Book', '1966-06-30');
insert into Books (BookID, Name, Type, PublicationDate) values (425, 'Whispers Across the Stardust Sea', 'Technical Book', '1928-09-09');
insert into Books (BookID, Name, Type, PublicationDate) values (426, 'Celestial Lullabies in Crimson Harmony', 'Biography', '2022-03-31');
insert into Books (BookID, Name, Type, PublicationDate) values (427, 'Ephemeral Dreams of the Celestial Voyager', 'Art Book', '1952-02-05');
insert into Books (BookID, Name, Type, PublicationDate) values (428, 'Sorcerer''s Symphony in Shifting Realms', 'Literary Book', '1973-08-05');
insert into Books (BookID, Name, Type, PublicationDate) values (429, 'The Celestial Odyssey of Astral Echoes', 'Literary Book', '1928-01-09');
insert into Books (BookID, Name, Type, PublicationDate) values (430, 'Echoes from the Celestial Garden', 'Literary Book', '1983-06-12');
insert into Books (BookID, Name, Type, PublicationDate) values (431, 'Crimson Sirens of the Enchanted Symphony', 'Literary Book', '1971-11-15');
insert into Books (BookID, Name, Type, PublicationDate) values (432, 'Astral Spells and Celestial Echoes', 'Biography', '1918-03-14');
insert into Books (BookID, Name, Type, PublicationDate) values (433, 'The Ethereal Dance of Forgotten Dreams', 'Technical Book', '1941-03-13');
insert into Books (BookID, Name, Type, PublicationDate) values (434, 'Sorcerer''s Soliloquy in Celestial Harmony', 'Technical Book', '1920-06-13');
insert into Books (BookID, Name, Type, PublicationDate) values (435, 'Ephemeral Whispers in the Astral Sky', 'Science Book', '1902-02-08');
insert into Books (BookID, Name, Type, PublicationDate) values (436, 'The Starborn Serenade of Stardust Realms', 'Biography', '1922-05-07');
insert into Books (BookID, Name, Type, PublicationDate) values (437, 'Chronicles of the Nebula''s Celestial Enchantment', 'Literary Book', '1905-11-18');
insert into Books (BookID, Name, Type, PublicationDate) values (438, 'Astral Dreams in the Forgotten Nocturne', 'Literary Book', '2013-11-17');
insert into Books (BookID, Name, Type, PublicationDate) values (439, 'Whispers of the Celestial Alchemist''s Garden', 'Science Book', '2019-11-29');
insert into Books (BookID, Name, Type, PublicationDate) values (440, 'The Celestial Waltz of Enchanted Echoes', 'Art Book', '2022-05-06');
insert into Books (BookID, Name, Type, PublicationDate) values (441, 'Echoes of the Astral Spellbook''s Symphony', 'Science Book', '1917-02-21');
insert into Books (BookID, Name, Type, PublicationDate) values (442, 'Crimson Portals of Stardust Dreams', 'Technical Book', '1997-04-04');
insert into Books (BookID, Name, Type, PublicationDate) values (443, 'Astral Labyrinth of Celestial Whispers', 'Literary Book', '2020-02-14');
insert into Books (BookID, Name, Type, PublicationDate) values (444, 'Sorcerer''s Sonata in Enchanted Harmony', 'Science Book', '1991-12-02');
insert into Books (BookID, Name, Type, PublicationDate) values (445, 'Ephemeral Whispers of the Celestial Embrace', 'Literary Book', '1909-11-17');
insert into Books (BookID, Name, Type, PublicationDate) values (446, 'The Ethereal Rhapsody of Astral Shadows', 'Literary Book', '2001-12-16');
insert into Books (BookID, Name, Type, PublicationDate) values (447, 'Celestial Nocturnes in Stardust Dreams', 'Science Book', '1942-03-20');
insert into Books (BookID, Name, Type, PublicationDate) values (448, 'Labyrinth of Astral Echoes and Portals', 'Science Book', '1957-03-28');
insert into Books (BookID, Name, Type, PublicationDate) values (449, 'The Enchanted Harmony of Celestial Shadows', 'Science Book', '1941-04-23');
insert into Books (BookID, Name, Type, PublicationDate) values (450, 'Whispers of the Ephemeral Astral Symphony', 'Technical Book', '1988-02-15');
insert into Books (BookID, Name, Type, PublicationDate) values (451, 'Chronicles of the Celestial Voyager''s Odyssey', 'Biography', '1927-12-11');
insert into Books (BookID, Name, Type, PublicationDate) values (452, 'Astral Tapestry of Stardust and Echoes', 'Art Book', '1923-01-07');
insert into Books (BookID, Name, Type, PublicationDate) values (453, 'Crimson Echoes of the Celestial Symphony', 'Science Book', '1919-11-15');
insert into Books (BookID, Name, Type, PublicationDate) values (454, 'Sorcerer''s Spellbook of Forgotten Dreams', 'Biography', '1953-01-13');
insert into Books (BookID, Name, Type, PublicationDate) values (455, 'Ephemeral Whispers in the Enchanted Garden', 'Technical Book', '1937-07-08');
insert into Books (BookID, Name, Type, PublicationDate) values (456, 'The Celestial Ballad of Celestial Portals', 'Biography', '1997-05-01');
insert into Books (BookID, Name, Type, PublicationDate) values (457, 'Songs of the Forgotten Astral Sea', 'Science Book', '1957-01-17');
insert into Books (BookID, Name, Type, PublicationDate) values (458, 'The Ethereal Waltz of Stardust Whispers', 'Technical Book', '2006-05-23');
insert into Books (BookID, Name, Type, PublicationDate) values (459, 'Crimson Serenade of Celestial Dreams', 'Science Book', '1985-02-04');
insert into Books (BookID, Name, Type, PublicationDate) values (460, 'Astral Sirens in the Enchanted Mist', 'Literary Book', '1955-03-06');
insert into Books (BookID, Name, Type, PublicationDate) values (461, 'Echoes of the Celestial Minstrel''s Symphony', 'Science Book', '1967-07-19');
insert into Books (BookID, Name, Type, PublicationDate) values (462, 'Chronicles of the Forgotten Astral Realm', 'Literary Book', '1911-01-13');
insert into Books (BookID, Name, Type, PublicationDate) values (463, 'The Enchanted Alchemy of Celestial Whispers', 'Art Book', '1941-01-19');
insert into Books (BookID, Name, Type, PublicationDate) values (464, 'Whispers Across the Stardust Sea', 'Science Book', '1939-03-26');
insert into Books (BookID, Name, Type, PublicationDate) values (465, 'Celestial Lullabies in Crimson Harmony', 'Literary Book', '1976-07-15');
insert into Books (BookID, Name, Type, PublicationDate) values (466, 'Ephemeral Dreams of the Celestial Voyager', 'Technical Book', '1945-07-29');
insert into Books (BookID, Name, Type, PublicationDate) values (467, 'Sorcerer''s Symphony in Shifting Realms', 'Literary Book', '1923-06-16');
insert into Books (BookID, Name, Type, PublicationDate) values (468, 'The Celestial Odyssey of Astral Echoes', 'Technical Book', '1928-03-24');
insert into Books (BookID, Name, Type, PublicationDate) values (469, 'Echoes from the Celestial Garden', 'Technical Book', '1988-05-23');
insert into Books (BookID, Name, Type, PublicationDate) values (470, 'Crimson Sirens of the Enchanted Symphony', 'Technical Book', '2018-12-21');
insert into Books (BookID, Name, Type, PublicationDate) values (471, 'Astral Spells and Celestial Echoes', 'Technical Book', '1999-05-22');
insert into Books (BookID, Name, Type, PublicationDate) values (472, 'The Ethereal Dance of Forgotten Dreams', 'Literary Book', '2001-11-26');
insert into Books (BookID, Name, Type, PublicationDate) values (473, 'Sorcerer''s Soliloquy in Celestial Harmony', 'Science Book', '2014-10-03');
insert into Books (BookID, Name, Type, PublicationDate) values (474, 'Ephemeral Whispers in the Astral Sky', 'Science Book', '1923-11-08');
insert into Books (BookID, Name, Type, PublicationDate) values (475, 'The Starborn Serenade of Stardust Realms', 'Science Book', '1984-12-21');
insert into Books (BookID, Name, Type, PublicationDate) values (476, 'Chronicles of the Nebula''s Celestial Enchantment', 'Literary Book', '1930-02-04');
insert into Books (BookID, Name, Type, PublicationDate) values (477, 'Astral Dreams in the Forgotten Nocturne', 'Technical Book', '2008-06-15');
insert into Books (BookID, Name, Type, PublicationDate) values (478, 'Whispers of the Celestial Alchemist''s Garden', 'Art Book', '1950-01-26');
insert into Books (BookID, Name, Type, PublicationDate) values (479, 'The Celestial Waltz of Enchanted Echoes', 'Art Book', '1907-09-30');
insert into Books (BookID, Name, Type, PublicationDate) values (480, 'Echoes of the Astral Spellbook''s Symphony', 'Literary Book', '1983-01-06');
insert into Books (BookID, Name, Type, PublicationDate) values (481, 'Crimson Portals of Stardust Dreams', 'Literary Book', '1937-09-18');
insert into Books (BookID, Name, Type, PublicationDate) values (482, 'Astral Labyrinth of Celestial Whispers', 'Literary Book', '1991-07-29');
insert into Books (BookID, Name, Type, PublicationDate) values (483, 'Sorcerer''s Sonata in Enchanted Harmony', 'Science Book', '1962-09-25');
insert into Books (BookID, Name, Type, PublicationDate) values (484, 'Ephemeral Whispers of the Celestial Embrace', 'Biography', '1916-02-02');
insert into Books (BookID, Name, Type, PublicationDate) values (485, 'The Ethereal Rhapsody of Astral Shadows', 'Literary Book', '1921-04-25');
insert into Books (BookID, Name, Type, PublicationDate) values (486, 'Celestial Nocturnes in Stardust Dreams', 'Technical Book', '1988-03-02');
insert into Books (BookID, Name, Type, PublicationDate) values (487, 'Labyrinth of Astral Echoes and Portals', 'Literary Book', '1984-09-25');
insert into Books (BookID, Name, Type, PublicationDate) values (488, 'The Enchanted Harmony of Celestial Shadows', 'Biography', '2006-10-28');
insert into Books (BookID, Name, Type, PublicationDate) values (489, 'Whispers of the Ephemeral Astral Symphony', 'Biography', '1984-08-09');
insert into Books (BookID, Name, Type, PublicationDate) values (490, 'Chronicles of the Celestial Voyager''s Odyssey', 'Biography', '1925-03-02');
insert into Books (BookID, Name, Type, PublicationDate) values (491, 'Astral Tapestry of Stardust and Echoes', 'Art Book', '1972-05-15');
insert into Books (BookID, Name, Type, PublicationDate) values (492, 'Crimson Echoes of the Celestial Symphony', 'Biography', '1933-09-01');
insert into Books (BookID, Name, Type, PublicationDate) values (493, 'Sorcerer''s Spellbook of Forgotten Dreams', 'Art Book', '1990-04-10');
insert into Books (BookID, Name, Type, PublicationDate) values (494, 'Ephemeral Whispers in the Enchanted Garden', 'Art Book', '1942-01-08');
insert into Books (BookID, Name, Type, PublicationDate) values (495, 'The Celestial Ballad of Celestial Portals', 'Art Book', '1978-04-24');
insert into Books (BookID, Name, Type, PublicationDate) values (496, 'Songs of the Forgotten Astral Sea', 'Art Book', '2011-12-16');
insert into Books (BookID, Name, Type, PublicationDate) values (497, 'The Ethereal Waltz of Stardust Whispers', 'Science Book', '2015-08-28');
insert into Books (BookID, Name, Type, PublicationDate) values (498, 'Crimson Serenade of Celestial Dreams', 'Science Book', '2004-02-12');
insert into Books (BookID, Name, Type, PublicationDate) values (499, 'Astral Sirens in the Enchanted Mist', 'Science Book', '1946-06-03');
insert into Books (BookID, Name, Type, PublicationDate) values (500, 'Echoes of the Celestial Minstrel''s Symphony', 'Technical Book', '2013-11-06');
